M48
; DRILL file {KiCad 9.0.8+dfsg-1} date 2026-10-04T14:25:51-0600
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-10-04T14:25:51-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.8+dfsg-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0748
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1181
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1339
%
G90
G05
T1
X5.63Y-4.1496
X6.063Y-4.1496
T2
X5.6496Y-4.0
X5.8465Y-3.9173
T3
X5.8465Y-4.1496
M30
