M48
; DRILL file {KiCad 9.0.8-4-g1ee99dff} date 2026-10-05T22:56:07-0600
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-10-05T22:56:07-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.8-4-g1ee99dff
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X148.8Y-51.5
X148.8Y-87.9
X186.7Y-51.5
X186.7Y-87.9
M30
