M48
; DRILL file {KiCad 9.0.8+dfsg-1} date 2026-10-06T21:35:35-0600
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-10-06T21:35:35-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.8+dfsg-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X5.8583Y-2.0276
X5.8583Y-3.4606
X7.3504Y-2.0276
X7.3504Y-3.4606
M30
