M48
; DRILL file {KiCad 9.0.8-4-g1ee99dff} date 2026-10-03T17:30:53-0600
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-10-03T17:30:53-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.8-4-g1ee99dff
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.400
%
G90
G05
T1
X143.001Y-105.4
X154.001Y-105.4
T2
X143.501Y-101.6
X148.501Y-99.5
T3
X148.501Y-105.4
M30
